function plan = buildfile
%BUILDFILE Reproducible ThermoWeave checks, tests, artifacts, and packaging.

import matlab.buildtool.Task
import matlab.buildtool.tasks.CleanTask
import matlab.buildtool.tasks.CodeIssuesTask
import matlab.buildtool.tasks.TestTask

% Built-in tasks provide standardized incremental behavior and CI formats.
plan = buildplan;
plan("clean") = CleanTask;
plan("check") = CodeIssuesTask(["src", "simscape", "examples", "tools", ...
    "startup.m", "runDemo.m"], ...
    Results="results/code-issues.sarif", WarningThreshold=Inf);
plan("test") = TestTask("tests", ...
    SourceFiles="src", ...
    Dependencies="check", ...
    TestResults="results/test-results.xml") ...
    .addCodeCoverage(["results/coverage.xml", "results/coverage.mat"]);

% Coverage interpretation is custom because the built-in task produces data
% but does not express this project's advisory 80% reporting threshold.
plan("coverage") = Task( ...
    Actions=@coverageTask, ...
    Dependencies="test", ...
    Description="Report advisory source coverage");

% Optional integration is separate so a missing/policy-gated model remains an
% explicit test outcome, not a fabricated core success.
plan("integration") = TestTask("tests/integration", ...
    SourceFiles=["src", "simscape"], ...
    Dependencies="check", ...
    TestResults="results/integration-results.xml");

% Artifact/docs/package actions have domain-specific outputs and therefore
% use small custom tasks. Each action logs through the build context.
plan("artifacts") = Task( ...
    Actions=@artifactTask, ...
    Dependencies="test", ...
    Description="Generate deterministic figures and web data", ...
    DisableIncremental=true);
plan("docs") = Task( ...
    Actions=@docsTask, ...
    Dependencies="artifacts", ...
    Description="Validate static documentation", ...
    DisableIncremental=true);
plan("package") = Task( ...
    Actions=@packageTask, ...
    Dependencies=["coverage", "docs"], ...
    Description="Build source and evidence archive", ...
    Outputs=["release/thermoweave-source.zip", ...
        "release/release-manifest.json"], ...
    DisableIncremental=true);

plan.DefaultTasks = ["check", "test", "coverage"];
end

function coverageTask(context)
coveragePath = fullfile(context.Plan.RootFolder, "results", "coverage.xml");
if ~isfile(coveragePath)
    context.log("No Cobertura coverage data was produced.");
    return
end
document = xmlread(coveragePath);
lineRate = str2double(string(document.getDocumentElement().getAttribute("line-rate")));
context.log(sprintf("Statement coverage: %.1f%%", 100 * lineRate));
if lineRate < 0.80
    context.log(sprintf("Advisory: coverage is below the 80%% target (%.1f%%).", ...
        100 * lineRate));
end
end

function artifactTask(context)
startup;
evidence = generateArtifacts();
context.assertTrue(isfile(evidence.figure), "Overview figure was not generated.");
context.assertTrue(isfile(evidence.webData.path), "Website data was not generated.");
context.log(sprintf("Generated %d website scenarios.", ...
    evidence.webData.scenarioCount));
context.assertTrue(isfile(evidence.experiments.path), ...
    "Experiment summary was not generated.");
context.assertTrue(isfile(evidence.study3d.reportPath), ...
    "3-D research summary was not generated.");
context.assertTrue(isfile(evidence.study3d.moduleFigurePath), ...
    "3-D module figure was not generated.");
end

function docsTask(context)
startup;
report = generateDocs();
context.assertTrue(report.status == "PASS", "Documentation validation failed.");
context.log(sprintf("Validated %d documentation entry points.", ...
    numel(report.files)));
end

function packageTask(context)
startup;
manifest = packageRelease();
context.assertTrue(isfile(manifest.archive), "Release archive was not created.");
context.log(sprintf("Release archive: %s (%d bytes)", ...
    manifest.archive, manifest.bytes));
end
