function result = makeResult(data,cfg,topo,metadata)
%MAKERESULT Construct thermoweave.result/v1 canonical structure.
result=struct('schemaVersion','thermoweave.result/v1','time_s',data.time_s(:), ...
 'state',struct('temperature_K',data.temperature_K,'soc',data.soc), ...
 'boundary',struct('temperature_K',data.boundaryTemperature_K,'conductance_W_per_K',data.boundaryConductance_W_per_K), ...
 'control',struct('zoneCommand',data.zoneCommand), ...
 'signals',struct('current_A',data.current_A(:),'heatGeneration_W',data.heatGeneration_W,'coolingPowerProxy_W',data.coolingPower_W(:)), ...
 'metrics',struct(),'topology',topo,'configuration',cfg,'metadata',metadata,'events',data.events);
result.metrics=thermoweave.results.computeMetrics(result,cfg);
end
