function manifest = exportWebData(outputPath)
%EXPORTWEBDATA Generate compact, traceable website data from simulations.

arguments
    outputPath (1, 1) string = fullfile(projectRoot(), "artifacts", ...
        "web-data", "thermoweave-demo.json")
end

root = projectRoot();
scenarioFiles = ["baseline.json", "vectorized-gradient.json", ...
    "nonuniform-cooling.json", ...
    "channel-restriction.json", "sensor-fault.json"];
template = struct( ...
    "id", "", "description", "", "boundaryMode", "", ...
    "time_s", [], "temperature_C", [], "boundaryTemperature_C", [], ...
    "zoneCommand", [], "metrics", struct, "scenarioHash", "", ...
    "sourceSchema", "");
records = repmat(template, numel(scenarioFiles), 1);

for index = 1:numel(scenarioFiles)
    config = thermoweave.config.loadScenario(fullfile(root, "config", ...
        scenarioFiles(index)));
    result = thermoweave.simulate(config);
    stride = max(1, floor(numel(result.time_s) / 90));
    sample = 1:stride:numel(result.time_s);
    if sample(end) ~= numel(result.time_s)
        sample(end + 1) = numel(result.time_s); %#ok<AGROW>
    end
    records(index) = struct( ...
        "id", string(result.configuration.scenario.id), ...
        "description", string(result.configuration.scenario.description), ...
        "boundaryMode", string(result.configuration.boundary.mode), ...
        "time_s", result.time_s(sample)', ...
        "temperature_C", result.state.temperature_K(sample, :) - 273.15, ...
        "boundaryTemperature_C", result.boundary.temperature_K(sample, :) - 273.15, ...
        "zoneCommand", result.control.zoneCommand(sample, :), ...
        "metrics", result.metrics, ...
        "scenarioHash", string(result.metadata.scenarioHash), ...
        "sourceSchema", string(result.schemaVersion));
end

payload = struct( ...
    "schemaVersion", "thermoweave.web/v1", ...
    "generatedBy", "tools/exportWebData.m", ...
    "matlabRelease", string(version("-release")), ...
    "syntheticData", true, ...
    "units", struct("temperature", "degC", "time", "s", ...
        "coolingEnergy", "J"), ...
    "scenarios", records);

folder = fileparts(outputPath);
if ~isfolder(folder)
    mkdir(folder);
end
text = jsonencode(payload);
file = fopen(outputPath, "w");
if file < 0
    error("thermoweave:web:IO", "Unable to open website data output.");
end
cleanup = onCleanup(@() fclose(file));
fwrite(file, text, "char");
manifest = struct("path", outputPath, "sha256", ...
    thermoweave.util.hashText(text), "bytes", strlength(text), ...
    "scenarioCount", numel(records));

docsPath = fullfile(root, "docs", "assets", "thermoweave-demo.json");
copyfile(outputPath, docsPath, "f");
end

function root = projectRoot()
root = fileparts(fileparts(mfilename("fullpath")));
end
