function manifest = runExperimentSuite(options)
%RUNEXPERIMENTSUITE Execute compact E0-E9 evidence runs and save JSON.

arguments
    options.MonteCarloRuns (1, 1) double {mustBeInteger,mustBePositive} = 20
    options.OutputPath (1, 1) string = fullfile(projectRoot(), ...
        "artifacts", "reports", "experiment-summary.json")
end

root = projectRoot();
run(fullfile(root, "startup.m"));
records = repmat(record("", "", "", struct, struct), 10, 1);

cfg = thermoweave.config.defaultConfig();
cfg.scenario.id = "E0-isothermal"; cfg.simulation.duration_s = 10;
cfg.cell.initialTemperature_K = 300; cfg.thermal.ambientTemperature_K = 300;
cfg.boundary.temperature_K = 300; cfg.electrical.current_A = 0;
cfg.controller.mode = "openloop"; e0 = thermoweave.simulate(cfg);
drift = max(abs(e0.state.temperature_K - 300), [], "all");
records(1) = record("E0", passFail(drift <= 1e-10 && ...
    e0.energyResidualNormalized <= 1e-10), "Isothermal sanity", ...
    compact(e0), struct("maximumDrift_K", drift));

cfg = thermoweave.config.loadScenario(fullfile(root, "config", ...
    "vectorized-gradient.json"));
e1 = thermoweave.simulate(cfg);
distinctBoundaryValues = numel(unique(e1.boundary.temperature_K(1, :)));
records(2) = record("E1", passFail(std(e1.boundary.temperature_K(1, :)) > 0 && ...
    numel(e1.boundary.temperature_K(1, :)) == cfg.cell.count && ...
    distinctBoundaryValues > 4 && ...
    all(isfinite(struct2array(e1.metrics))) && ...
    string(e1.metadata.scenarioHash) == ...
    string(thermoweave.util.hashStruct(e1.configuration)) && ...
    e1.energyResidualNormalized <= 1e-4), ...
    "Prescribed spatial gradient", compact(e1), ...
    struct("distinctBoundaryValues", distinctBoundaryValues));

cfg = thermoweave.config.defaultConfig(); cfg.scenario.id = "E2-coolant";
cfg.boundary.mode = "coolant"; cfg.controller.mode = "openloop";
cfg.electrical.current_A = 0; cfg.simulation.duration_s = 20;
cfg.simulation.outputStep_s = 2;
cfg.cell.initialTemperature_K = linspace(299, 304, cfg.cell.count)';
topology = thermoweave.thermal.buildTopology(cfg.layout);
cfg.boundary.coolant.segmentNodes = topology.zoneId; e2f = thermoweave.simulate(cfg);
cfg.boundary.coolant.segmentNodes = 1 + max(topology.zoneId) - topology.zoneId;
e2r = thermoweave.simulate(cfg);
patternDifference = max(abs(e2f.state.temperature_K(end, :) - ...
    e2r.state.temperature_K(end, :)));
temperatureSample = cfg.cell.initialTemperature_K;
forwardMap = zeros(cfg.cell.count, cfg.boundary.coolant.segments);
for index = 1:cfg.cell.count
    forwardMap(index, topology.zoneId(index)) = ...
        cfg.boundary.coolant.segmentConductance_W_per_K;
end
[coolantTemperature, coolantHeat] = thermoweave.coolant.march( ...
    temperatureSample, forwardMap, cfg.boundary.coolant.inletTemperature_K, ...
    cfg.boundary.coolant.massFlow_kg_per_s, ...
    cfg.boundary.coolant.specificHeat_J_per_kgK);
coolantBalanceError = abs(sum(coolantHeat) - ...
    cfg.boundary.coolant.massFlow_kg_per_s * ...
    cfg.boundary.coolant.specificHeat_J_per_kgK * ...
    (coolantTemperature(end) - cfg.boundary.coolant.inletTemperature_K));
records(3) = record("E2", passFail(patternDifference > 1e-6 && ...
    coolantBalanceError <= 1e-9 && e2f.energyResidualNormalized <= 1e-4 && ...
    e2r.energyResidualNormalized <= 1e-4), ...
    "Coolant forward/reverse", compact(e2f), ...
    struct("reversePatternDifference_K", patternDifference, ...
    "reverseResidual", e2r.energyResidualNormalized, ...
    "coolantBalanceError_W", coolantBalanceError));

cfg = thermoweave.config.defaultConfig(); cfg.scenario.id = "E3-zonal-control";
cfg.simulation.duration_s = 300; cfg.simulation.outputStep_s = 2;
cfg.electrical.currentProfile = struct("time_s", [0; 60; 240; 241; 300], ...
    "current_A", [0; 10; 10; 0; 0]); cfg.electrical.current_A = 0;
openConfig = cfg; openConfig.controller.mode = "openloop";
baseConfig = cfg; baseConfig.controller.mode = "baseline";
e3Open = thermoweave.simulate(openConfig); e3Base = thermoweave.simulate(baseConfig);
openRise = e3Open.metrics.peakTemperature_K - cfg.cell.initialTemperature_K;
baseRise = e3Base.metrics.peakTemperature_K - cfg.cell.initialTemperature_K;
benefit = (openRise - baseRise) / max(openRise, eps);
records(4) = record("E3", passFail(benefit >= 0.15 && ...
    e3Base.metrics.peakTemperature_K <= 318.15 && ...
    max([e3Open.energyResidualNormalized e3Base.energyResidualNormalized]) ...
    <= 1e-4), ...
    "Zonal controller challenge", compact(e3Base), ...
    struct("peakRiseReductionFraction", benefit, ...
    "openLoopPeakTemperature_K", e3Open.metrics.peakTemperature_K));

seeds = (4401:4403)'; peaks = zeros(size(seeds)); hashes = strings(size(seeds));
drawsPositive = true(size(seeds)); repeatedExact = false;
for index = 1:numel(seeds)
    cfg = thermoweave.config.defaultConfig(); cfg.scenario.id = "E4-variability";
    cfg.simulation.duration_s = 120; cfg.simulation.outputStep_s = 2;
    cfg.simulation.seed = seeds(index); cfg.variability.enabled = true;
    cfg.variability.seed = seeds(index); cfg.electrical.current_A = 10;
    result = thermoweave.simulate(cfg); peaks(index) = result.metrics.peakTemperature_K;
    hashes(index) = string(result.metadata.scenarioHash);
    draws = result.metadata.variability.draws;
    drawsPositive(index) = all(draws.R0_Ohm > 0) && ...
        all(draws.capacity_J_per_K > 0) && ...
        all(draws.ambientConductance_W_per_K > 0) && ...
        all(draws.edgeConductanceScale > 0) && ...
        all(draws.coolantCellConductanceScale > 0);
    if index == 1
        repeated = thermoweave.simulate(cfg);
        repeatedExact = strcmp(jsonencode(result), jsonencode(repeated));
    end
end
records(5) = record("E4", passFail(all(isfinite(peaks)) && ...
    all(drawsPositive) && repeatedExact && ...
    numel(unique(hashes)) == numel(seeds)), "Seeded cell variability", ...
    struct("peakTemperature_K", max(peaks)), ...
    struct("seeds", seeds, "peakTemperature_K", peaks, ...
    "scenarioHashes", hashes, "drawsPositive", drawsPositive, ...
    "firstSeedRepeatedExactly", repeatedExact));

cfg = thermoweave.config.loadScenario(fullfile(root, "config", ...
    "channel-restriction.json")); e5 = thermoweave.simulate(cfg);
topology = thermoweave.thermal.buildTopology(cfg.layout);
temperatureSample = repmat(300, cfg.cell.count, 1);
before = thermoweave.coolant.evaluate(temperatureSample, cfg, topology, [], 0);
active = thermoweave.coolant.evaluate(temperatureSample, cfg, topology, [], 180);
targetFactor = sum(active.Hcool_W_per_K(:, 2)) / ...
    sum(before.Hcool_W_per_K(:, 2));
otherUnchanged = isequal(active.Hcool_W_per_K(:, [1 3 4]), ...
    before.Hcool_W_per_K(:, [1 3 4]));
records(6) = record("E5", passFail(any(strcmp({e5.events.type}, ...
    'coolant_blockage')) && abs(targetFactor-0.2) <= 1e-12 && ...
    otherUnchanged && e5.energyResidualNormalized <= 1e-4), ...
    "Segment-2 channel restriction", compact(e5), ...
    struct("faultTarget", 2, "measuredConductanceFactor", targetFactor, ...
    "otherSegmentsUnchanged", otherUnchanged));

cfg = thermoweave.config.loadScenario(fullfile(root, "config", ...
    "sensor-fault.json")); e6 = thermoweave.simulate(cfg);
canonicalDimensions = isequal(size(e6.state.temperature_K), ...
    [numel(e6.time_s) cfg.cell.count]) && isequal(size(e6.state.soc), ...
    [numel(e6.time_s) cfg.cell.count]);
records(7) = record("E6", passFail(any(strcmp({e6.events.type}, ...
    'sensor_bias')) && canonicalDimensions && ...
    e6.energyResidualNormalized <= 1e-4), "Zone-2 sensor bias", compact(e6), ...
    struct("faultTarget", 2, "bias_K", 5));

cfg = thermoweave.config.defaultConfig(); cfg.scenario.id = "E7-controller";
cfg.simulation.duration_s = 180; cfg.simulation.outputStep_s = 2;
cfg.electrical.current_A = 18;
openConfig = cfg; openConfig.controller.mode = "openloop";
baseConfig = cfg; baseConfig.controller.mode = "baseline";
advancedConfig = cfg; advancedConfig.controller.mode = "advanced";
e7Open = thermoweave.simulate(openConfig); e7Base = thermoweave.simulate(baseConfig);
e7Advanced = thermoweave.simulate(advancedConfig);
commandsBounded = all(e7Base.control.zoneCommand >= 0, "all") && ...
    all(e7Base.control.zoneCommand <= 1, "all") && ...
    all(e7Advanced.control.zoneCommand >= 0, "all") && ...
    all(e7Advanced.control.zoneCommand <= 1, "all");
finiteComparison = all(isfinite([e7Open.metrics.peakTemperature_K, ...
    e7Base.metrics.peakTemperature_K, e7Advanced.metrics.peakTemperature_K]));
records(8) = record("E7", passFail(commandsBounded && finiteComparison && ...
    max([e7Open.energyResidualNormalized e7Base.energyResidualNormalized ...
    e7Advanced.energyResidualNormalized]) <= 1e-4), "Controller comparison", ...
    compact(e7Base), struct( ...
    "openLoopPeakTemperature_K", e7Open.metrics.peakTemperature_K, ...
    "advancedPeakTemperature_K", e7Advanced.metrics.peakTemperature_K, ...
    "advancedFallbackEvents", sum(strcmp({e7Advanced.events.type}, ...
    'controller_fallback')), "commandsBounded", commandsBounded, ...
    "benefitClaim", "descriptive-only"));

mcSeeds = (6100:(6100 + options.MonteCarloRuns - 1))';
mcPeaks = zeros(size(mcSeeds)); mcEnergy = zeros(size(mcSeeds));
for index = 1:numel(mcSeeds)
    cfg = thermoweave.config.defaultConfig(); cfg.scenario.id = "E8-monte-carlo";
    cfg.simulation.duration_s = 120; cfg.simulation.outputStep_s = 2;
    cfg.simulation.seed = mcSeeds(index); cfg.variability.enabled = true;
    cfg.variability.seed = mcSeeds(index);
    result = thermoweave.simulate(cfg); mcPeaks(index) = result.metrics.peakTemperature_K;
    mcEnergy(index) = result.metrics.coolingEnergy_J;
end
records(9) = record("E8", passFail(all(isfinite(mcPeaks)) && ...
    numel(unique(mcSeeds)) == options.MonteCarloRuns), ...
    "Seeded Monte Carlo summary", ...
    struct("peakTemperature_K", max(mcPeaks), ...
    "coolingEnergy_J", mean(mcEnergy)), ...
    struct("runCount", numel(mcSeeds), "firstSeed", mcSeeds(1), ...
    "lastSeed", mcSeeds(end), "peakTemperature95th_K", percentile(mcPeaks, 95)));

adapter = runSimscapeScenario(thermoweave.config.defaultConfig(), ...
    ProjectRoot=string(root));
records(10) = record("E9", string(adapter.status), ...
    "Core versus optional Simscape adapter", struct, ...
    struct("adapterStatus", string(adapter.status), ...
    "message", string(adapter.message)));

payload = struct("schemaVersion", "thermoweave.experiments/v1", ...
    "syntheticData", true, "matlabRelease", string(version("-release")), ...
    "scenarioSpecification", "docs/scenarios.md", "records", records);
folder = fileparts(options.OutputPath); if ~isfolder(folder), mkdir(folder); end
text = jsonencode(payload); file = fopen(options.OutputPath, "w");
if file < 0, error("thermoweave:experiments:IO", "Unable to write experiment summary."); end
cleanup = onCleanup(@() fclose(file)); fwrite(file, text, "char");
manifest = struct("path", options.OutputPath, ...
    "sha256", thermoweave.util.hashText(text), "scenarioCount", numel(records), ...
    "monteCarloRuns", options.MonteCarloRuns);
end

function output = compact(result)
output = struct("peakTemperature_K", result.metrics.peakTemperature_K, ...
    "peakEdgeGradient_K", result.metrics.peakEdgeGradient_K, ...
    "coolingEnergy_J", result.metrics.coolingEnergy_J, ...
    "energyResidualNormalized", result.energyResidualNormalized, ...
    "scenarioHash", string(result.metadata.scenarioHash));
end
function output = record(id,status,description,metrics,evidence)
output = struct("id",string(id),"status",string(status), ...
    "description",string(description),"metrics",metrics,"evidence",evidence);
end
function status = passFail(condition)
if condition, status = "PASS"; else, status = "FAIL"; end
end
function value = percentile(values, probability)
values = sort(values(:)); position = 1 + (numel(values)-1)*probability/100;
lower = floor(position); upper = ceil(position);
if lower == upper, value = values(lower); else, value = values(lower) + ...
        (position-lower)*(values(upper)-values(lower)); end
end
function root = projectRoot()
root = fileparts(fileparts(mfilename("fullpath")));
end
