function cfg = defaultConfig()
%DEFAULTCONFIG Return the synthetic, portable ThermoWeave scenario.
cfg = struct();
cfg.schemaVersion = 'thermoweave.config/v1';
cfg.scenario = struct('id','default','description','synthetic reference');
cfg.simulation = struct('duration_s',600,'outputStep_s',1,'solver','ode15s', ...
    'relativeTolerance',1e-6,'absoluteTolerance',1e-8,'maxStep_s',0.25,'seed',0);
cfg.layout = struct('type','rectangular','rows',3,'columns',4,'pitchX_m',0.03,'pitchY_m',0.03, ...
    'gx_W_per_K',0.80,'gy_W_per_K',0.60,'edgeConductance_W_per_K',0.70,'zoneCount',4);
cfg.cell = struct('count',12,'initialTemperature_K',298.15,'initialSOC',0.8, ...
    'mass_kg',0.045,'specificHeat_J_per_kgK',900,'thermalCapacity_J_per_K',40.5, ...
    'area_m2',0.001,'zoneWeights',[]);
cfg.thermal = struct('ambientTemperature_K',298.15,'ambientConductance_W_per_K',0.25, ...
    'contactConductance_W_per_K',[],'externalHeat_W',0);
cfg.electrical = struct('current_A',5,'currentProfile',[],'capacity_C',18000, ...
    'capacity_Ah',5,'R0_Ohm',0.008,'alphaT_per_K',0.003,'alphaSOC',0.05, ...
    'temperatureReference_K',298.15,'dischargeEfficiency',1,'chargeEfficiency',1, ...
    'entropicHeat',false,'dUoc_dT_V_per_K',0.0002);
cfg.boundary = struct('mode','scalar','temperature_K',298.15,'conductance_W_per_K',0.25, ...
    'zoneTemperature_K',[],'zoneConductance_W_per_K',[],'zoneId',[], ...
    'coolant',struct('segments',4,'massFlow_kg_per_s',0.010,'specificHeat_J_per_kgK',3800, ...
        'inletTemperature_K',298.15,'segmentConductance_W_per_K',2.0,'segmentNodes',[]));
cfg.controller = struct('mode','baseline','referenceTemperature_K',298.15,'samplePeriod_s',2, ...
    'Kp_per_K',0.20,'qMax_W',25,'rateLimit_per_s',Inf,'deadband_K',0, ...
    'zoneCount',4,'advanced',struct('horizon',20,'lambdaU',0.1,'lambdaE',0.01, ...
    'lambdaGradient',0.1));
cfg.variability = struct('enabled',false,'seed',0,'R0CV',0.05,'uniformFraction',0.10);
cfg.faults = struct('events',[]);
cfg.metrics = struct('temperatureThreshold_K',318.15,'edgeGradientLimit_K',Inf,'socBounds',[0 1]);
end
